services:
  postgres:
    image: postgres:latest
    container_name: hutech-bot_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: hutech-bot_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  hutech-bot:
    build: .
    image: hutech-bot:latest
    container_name: hutech-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: